routes/admin.php
<?php

Route::get('/home', function () {
    /**
    $users[] = Auth::user();
    $users[] = Auth::guard()->user();
    $users[] = Auth::guard('admin')->user();

    //dd($users);

    return view('admin.home');
    /**/
    return redirect(route('admin.dashboard'));
})->name('home');

Route::get('/dashboard', function () {
    $users[] = Auth::user();
    $users[] = Auth::guard()->user();
    $users[] = Auth::guard('admin')->user();

    //dd($users);

    return view('admin.dashboard');
})->name('dashboard');

Route::get('/template', function () {
    $users[] = Auth::user();
    $users[] = Auth::guard()->user();
    $users[] = Auth::guard('admin')->user();

    //dd($users);

    return view('admin.template');
})->name('template');

Route::get('/invoice',function(){
	return view('admin.invoice');
})->name('invoice');

Route::get('/print-invoice',function(){
	/**
	$pdf = PDF::loadView('admin.orders.invoice',compact('data','data1','data2','Order_Code','Visitor'));
	return $pdf->download('OrderInvoice-'.$Order_Code.'.pdf');
	/**/
	$pdf = PDF::loadView('admin.invoice');
	return $pdf->download('OrderInvoice_dated_'.date('d-m-Y').'.pdf');
})->name('print-invoice');

routes/user.php
<?php

Route::get('/home', function () {
    $users[] = Auth::user();
    $users[] = Auth::guard()->user();
    $users[] = Auth::guard('user')->user();

    //dd($users);

    return view('user.home');
})->name('home');

routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', function () {
    return view('index');
})->name('home');

Route::get('/about', function () {
    return view('about');
})->name('about');

Route::get('/about/contact-us', function () {
    return view('contact-us');
})->name('contact-us');

Route::get('/welcome', function () {
    return view('welcome');
});

Route::group(['prefix' => 'admin', 'as' => 'admin.'], function () {
    Route::get('/', function () {
        return redirect(route('admin.login'));
    });
	Route::get('/login', 'AdminAuth\LoginController@showLoginForm')->name('login');
	Route::post('/login', 'AdminAuth\LoginController@login');
	Route::post('/logout', 'AdminAuth\LoginController@logout')->name('logout');

	Route::get('/register', 'AdminAuth\RegisterController@showRegistrationForm')->name('register');
	Route::post('/register', 'AdminAuth\RegisterController@register');

	Route::post('/password/email', 'AdminAuth\ForgotPasswordController@sendResetLinkEmail')->name('password.request');
	Route::post('/password/reset', 'AdminAuth\ResetPasswordController@reset')->name('password.email');
	Route::get('/password/reset', 'AdminAuth\ForgotPasswordController@showLinkRequestForm')->name('password.reset');
	Route::get('/password/reset/{token}', 'AdminAuth\ResetPasswordController@showResetForm');
});

Route::group(['prefix' => 'user', 'as' => 'user.'], function () {
	Route::get('/login', 'UserAuth\LoginController@showLoginForm')->name('login');
	Route::post('/login', 'UserAuth\LoginController@login');
	Route::post('/logout', 'UserAuth\LoginController@logout')->name('logout');
	
	Route::get('/register', 'UserAuth\RegisterController@showRegistrationForm')->name('register');
	Route::post('/register', 'UserAuth\RegisterController@register');
	
	Route::post('/password/email', 'UserAuth\ForgotPasswordController@sendResetLinkEmail')->name('password.request');
	Route::post('/password/reset', 'UserAuth\ResetPasswordController@reset')->name('password.email');
	Route::get('/password/reset', 'UserAuth\ForgotPasswordController@showLinkRequestForm')->name('password.reset');
	Route::get('/password/reset/{token}', 'UserAuth\ResetPasswordController@showResetForm');
});

resources/views/layout/app.blade.php
<!doctype html>
<html lang="{{ app()->getLocale() }}">
    <head>
        <meta charset="utf-8">
        <meta http-equiv="X-UA-Compatible" content="IE=edge">
        <meta name="viewport" content="width=device-width, initial-scale=1">

        <title>Laravel</title>

        <!-- Fonts -->
        <link href="https://fonts.googleapis.com/css?family=Raleway:100,600" rel="stylesheet" type="text/css">

        <!-- Styles -->
        <style>
            html, body {
                background-color: #fff;
                color: #636b6f;
                font-family: 'Raleway', sans-serif;
                font-weight: 100;
                height: 100vh;
                margin: 0;
            }

            .full-height {
                height: 100vh;
            }

            .flex-center {
                align-items: center;
                display: flex;
                justify-content: center;
            }

            .position-ref {
                position: relative;
            }

            .top-right {
                position: absolute;
                right: 10px;
                top: 18px;
            }

            .content {
                text-align: center;
            }

            .title {
                font-size: 84px;
            }

            .links > a {
                color: #636b6f;
                padding: 0 25px;
                font-size: 12px;
                font-weight: 600;
                letter-spacing: .1rem;
                text-decoration: none;
                text-transform: uppercase;
            }

            .m-b-md {
                margin-bottom: 30px;
            }
            .active{
                font-weight: 600;
                text-decoration: underline;
            }
        </style>
    </head>
    <body>
        <div class="flex-center position-ref full-height">
            @if (Route::has('user.login'))
                <div class="top-right links">
                    @if(Auth::guard('admin')->check())
                        <a href="{{ route('admin.home') }}" target="_blank">Admin Panel</a>
                    @endif
                    <a href="{{ route('home') }}"><span class="{{ (Route::current()->getName() == 'home') ? 'active' : '' }}">Home</span></a>
                    <a href="{{ route('about') }}"><span class="{{ (Route::current()->getName() == 'about') || Request::is('about/*') ? 'active' : '' }}">About</span></a>
                    <a href="{{ route('contact-us') }}"><span class="{{ (Route::current()->getName() == 'contact-us') ? 'active' : '' }}">Contact Us</span></a>
                    @if(Auth::guard('user')->check())
                        <a href="{{ route('user.home') }}">My Account</a>
                    @else
                        <a href="{{ route('user.login') }}">Login</a>
                        <a href="{{ route('user.register') }}">Register</a>
                    @endif
                </div>
            @endif

            @yield('content')

        </div>
    </body>
</html>